apiVersion: v2
publisher: fbenoit
name: intellij-NOVNC
version: 2020.2.2
type: Che Editor
displayName:  IntelliJ IDEA Community Edition
title:  IntelliJ IDEA Community Edition (in browser using noVNC) as editor for Eclipse Che
description:  IntelliJ IDEA Community Edition running on the Web with noVNC
icon: https://resources.jetbrains.com/storage/products/intellij-idea/img/meta/intellij-idea_logo_300x300.png
category: Editor
repository: https://github.com/benoitf/intellij-editor-vnc/
firstPublicationDate: "2020-09-07"
spec:
  endpoints:
  # hack (use dirigible endpoint name as it is part of liveness probes)
   -  name: "dirigible"
      public: true
      targetPort: 8080
      attributes:
        protocol: http
        type: ide
        path: /vnc.html?resize=remote&autoconnect=true&reconnect=true
  containers:
   - name: intellij-novnc
     image: "vzhukovs/che-editor-intellij:latest"
     mountSources: true
     volumes:
         - mountPath: "/intellij-config"
           name: intellij-config     
     volumes:
         - mountPath: "/home/user/.local"
           name: intellij-local
     volumes:
         - mountPath: "/home/user/.java"
           name: intellij-java
     ports:
         - exposedPort: 8080
     memoryLimit: "2048M"
     
